### PR TITLE
Benson

### PR DESCRIPTION
**Pull request by Ben1464**
Added a Header component that consist of the name of the project and a dark mode toggle .

### CODE REVIEW

**Comment by ussenuk** [comment]
the added component was good but need some adjustment

**Review by Ben1464 — COMMENTED** [review]
Added a footer component

**Review by ussenuk — CHANGES_REQUESTED** [review]
we need to create a new add these new changes after merging the Mark code

**Comment by ussenuk** [comment]
we need to request a new pull after downloading the Mark code to avoid conflicts

**Pull request closed without merging**
